[package]
name = "td_clua"
version = "0.1.0"
authors = ["wugd"]
description = "Bindings for Lua 5.3"
build = "build.rs"
links = "lua"
license = "MIT/Apache-2.0"

[build-dependencies]
pkg-config = "0.3"
gcc = "0.3"

[dependencies]
libc = "*"
