[package]
name = "c_lua"
version = "0.0.4"
authors = ["wugd"]
description = "Bindings for Lua 5.3"
build = "build.rs"
links = "lua"
license = "MIT"

[build-dependencies]
pkg-config = "0.3"
gcc = "0.3"

[dependencies]
libc = "*"
